services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    # For airflow local postgres
    networks:
      - airflow
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   volumes:
  #     - ./data_pgadmin:/var/lib/pgadmin
  #   ports:
  #     - 8080:80

# For airflow local postgres
networks:
  airflow:
    external:
      name: airflow_default